[package]
name = "db_merge_sort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
cute = "0.3.0"
num = "0.4.1"
rand = "0.8.5"
serde = "1.0.190"
serde_derive = "1.0.190"
